name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '40 22 5/15 * *'

jobs:
  docker:
    name: slackware64-${{ matrix.version }}
    strategy:
      fail-fast: true
      matrix:
        version: [15.0, current]
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Make
        run: sudo ./mktar.sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: RELEASE=slackware64-${{ matrix.version }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slackware:${{ matrix.version }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache,mode=max
