name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '40 22 5/15 * *'

jobs:
  docker_stable:
    runs-on: ubuntu-latest
    env:
      RELEASE: slackware64-15.0
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Make
        run: sudo ./mktar.sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: RELEASE=${{ env.RELEASE }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slackware:15.0
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache,mode=max

  docker_current:
    runs-on: ubuntu-latest
    env:
      RELEASE: slackware64-current
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Make
        run: sudo RELEASE=${{ env.RELEASE }} ./mktar.sh
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: RELEASE=${{ env.RELEASE }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slackware:current
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache,mode=max
