name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'release'
        required: true
        default: 'slackware64-15.0'
        type: string
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Make
        run: make image RELEASE=${{ inputs.release }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: RELEASE=${{ inputs.release }}
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/slackware:15.0
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/slackware:buildcache,mode=max
